name: Validate Exercises

on:
  workflow_dispatch:   # 👈 allows manual trigger from the Actions tab
  push:
    paths:
      - 'exercises-repo/**'
      - '.github/workflows/validate-exercises.yml'
  pull_request:
    paths:
      - 'exercises-repo/**'
      - '.github/workflows/validate-exercises.yml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sympy

      - name: Run validator
        run: |
          set -o pipefail
          python exercises-repo/validate_exercises.py exercises-repo/exercises.json | tee exercises-repo/validation_summary.txt

      - name: Upload validation report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-logs
          path: exercises-repo/validation_summary.txt
